export const tracks = [
    {
        id: 1,
        title: "Lose Yourself",
        artist: "Eminem",
        genre: "Hip-Hop",
        year: 2002,
        album: "8 Mile Soundtrack",
        label: "Shady Records",
        producer: "Eminem, Jeff Bass, Luis Resto",
        duration: "5:26",
        image: "./images/eminem.jpeg"
    },
    {
        id: 2,
        title: "Alright",
        artist: "Kendrick Lamar",
        genre: "Hip-Hop",
        year: 2015,
        album: "To Pimp a Butterfly",
        label: "Top Dawg Entertainment",
        producer: "Pharrell Williams, Sounwave",
        duration: "3:39",
        image: "./images/kendrik-lamar.jpeg"
    },
    {
        id: 3,
        title: "No Scrubs",
        artist: "TLC",
        genre: "R&B",
        year: 1999,
        album: "FanMail",
        label: "LaFace Records",
        producer: "Kevin 'She'kspere' Briggs",
        duration: "3:35",
        image: "./images/tlc.jpeg"
    },
    {
        id: 4,
        title: "Sicko Mode",
        artist: "Travis Scott",
        genre: "Trap",
        year: 2018,
        album: "Astroworld",
        label: "Epic Records",
        producer: "Hit-Boy, Tay Keith, Mike Dean",
        duration: "5:13",
        image: "./images/travis-scott.jpeg"
    },
    {
        id: 5,
        title: "Redbone",
        artist: "Childish Gambino",
        genre: "Soul",
        year: 2016,
        album: "Awaken, My Love!",
        label: "Glassnote Records",
        producer: "Ludwig Göransson",
        duration: "5:27",
        image: "./images/childish-gambino.jpeg"
    },
    {
        id: 6,
        title: "Juicy",
        artist: "The Notorious B.I.G.",
        genre: "Hip-Hop",
        year: 1994,
        album: "Ready to Die",
        label: "Bad Boy Records",
        producer: "Poke, Sean Combs",
        duration: "5:03",
        image: "./images/big.jpeg"
    },
    {
        id: 7,
        title: "Crazy in Love",
        artist: "Beyoncé ft. Jay-Z",
        genre: "R&B",
        year: 2003,
        album: "Dangerously in Love",
        label: "Columbia Records",
        producer: "Rich Harrison",
        duration: "3:56",
        image: "./images/beyonce.jpeg"
    },
    {
        id: 8,
        title: "HUMBLE.",
        artist: "Kendrick Lamar",
        genre: "Hip-Hop",
        year: 2017,
        album: "DAMN.",
        label: "Top Dawg Entertainment",
        producer: "Mike Will Made-It",
        duration: "2:57",
        image: "./images/humble.jpeg"
    },
    {
        id: 9,
        title: "Mask Off",
        artist: "Future",
        genre: "Trap",
        year: 2017,
        album: "Future",
        label: "Epic Records",
        producer: "Metro Boomin",
        duration: "3:24",
        image: "./images/future.jpeg"
    },
    {
        id: 10,
        title: "Untitled (How Does It Feel)",
        artist: "D'Angelo",
        genre: "Soul",
        year: 2000,
        album: "Voodoo",
        label: "Virgin Records",
        producer: "D'Angelo, Raphael Saadiq",
        duration: "7:10",
        image: "./images/d-angelo.jpeg"
    },
    {
        id: 11,
        title: "Old Town Road",
        artist: "Lil Nas X ft. Billy Ray Cyrus",
        genre: "Hip-Hop",
        year: 2019,
        album: "7 EP",
        label: "Columbia Records",
        producer: "YoungKio",
        duration: "2:37",
        image: "./images/lil-nas.jpeg"
    },
    {
        id: 12,
        title: "Adorn",
        artist: "Miguel",
        genre: "R&B",
        year: 2012,
        album: "Kaleidoscope Dream",
        label: "RCA Records",
        producer: "Miguel",
        duration: "3:19",
        image: "./images/miguel.jpeg"
    },
    {
        id: 13,
        title: "God's Plan",
        artist: "Drake",
        genre: "Hip-Hop",
        year: 2018,
        album: "Scorpion",
        label: "Young Money Entertainment",
        producer: "Cardo, Yung Exclusive, Boi-1da",
        duration: "3:19",
        image: "./images/drake.jpeg"
    },
    {
        id: 14,
        title: "XO Tour Llif3",
        artist: "Lil Uzi Vert",
        genre: "Trap",
        year: 2017,
        album: "Luv Is Rage 2",
        label: "Atlantic Records",
        producer: "TM88, JW Lucas",
        duration: "3:03",
        image: "./images/lil-vert.jpeg"
    },
    {
        id: 15,
        title: "Thinking Bout You",
        artist: "Frank Ocean",
        genre: "R&B",
        year: 2012,
        album: "Channel Orange",
        label: "Def Jam Recordings",
        producer: "Shea Taylor",
        duration: "3:21",
        image: "./images/frank-ocean.jpeg"
    },
    {
        id: 16,
        title: "Hotline Bling",
        artist: "Drake",
        genre: "R&B",
        year: 2015,
        album: "Views",
        label: "Cash Money Records",
        producer: "Nineteen85",
        duration: "4:27",
        image: "./images/drake2.jpeg"
    },
    {
        id: 17,
        title: "The Box",
        artist: "Roddy Ricch",
        genre: "Trap",
        year: 2019,
        album: "Please Excuse Me for Being Antisocial",
        label: "Atlantic Records",
        producer: "30 Roc, Dat Boi Squeeze",
        duration: "3:16",
        image: "./images/roddy-ricch.jpeg"
    },
    {
        id: 18,
        title: "Best Part",
        artist: "Daniel Caesar ft. H.E.R.",
        genre: "R&B",
        year: 2017,
        album: "Freudian",
        label: "Golden Child Recordings",
        producer: "Jordan Evans, Matthew Burnett",
        duration: "3:30",
        image: "./images/her.jpeg"
    }
];
